import {
  LayoutDashboard,
  Briefcase,
  Code,
  MessageSquare,
  BookUser,
  MessageSquareText,
  Type,
  Link2,
  FileText,
  History,
  HelpCircle,
  Reply,
  Sparkles,
  UserCircle,
  Globe,
  Palette,
  Headset,
  Users,
  Plug,
  Settings,
  ChartLine,
  Key,
  UserStar,
  Zap,
  CreditCard,
  BadgeCheck,
  Database,
  MessagesSquare,
  Eye,
  RotateCcw,
  RefreshCw,
  Boxes,
  Layers,
  EyeOff,
} from "lucide-react";

export const SEARCH_GROUPS = {
  pages: "Pages",
  knowledge: "Knowledge Base",
  customizations: "Customizations",
  settings: "Settings",
  advanced: "Advanced",
  account: "Account",
  sdk: "SDK Advanced",
};

/**
 * Static navigation index for the Ctrl+K search palette.
 *
 * Entry shape:
 *   id       - stable unique key (also used as the cmdk item value)
 *   title    - primary label shown in the palette
 *   url      - bare pathname, never pre-encoded with ? or #
 *   tab      - optional ?tab= value, resolved by buildHref
 *   hash     - optional #anchor id, resolved by buildHref (requires the target
 *              page to render that id AND call useHashScroll)
 *   section  - display-only breadcrumb shown next to the title
 *   icon     - lucide component reference (this is why the index is .js, not .json)
 *   group    - key of SEARCH_GROUPS
 *   keywords - extra search terms; matched by Fuse, NOT by cmdk's own filter
 *
 * Keyword convention: write what a confused user types, not what the feature is
 * called. "talk to human" and "running out" earn their place; "leads" on the
 * Leads entry does not, since the title already covers it. Multi-word phrases
 * are fine — Fuse runs with ignoreLocation, so it matches anywhere in the string.
 *
 * Known ceiling: keywords only relate phrasings someone thought of in advance.
 * The planned fix is offline semantic search — embed each entry at build time,
 * ship the vectors as static JSON, score cosine similarity in the browser. That
 * buys "how do I stop it replying at night" -> Chatbot Instructions with nothing
 * hand-written. Deliberately deferred: at this index size curated keywords plus
 * the fuzzy fallback in SearchCommand still catch more than they miss, and a
 * build step plus shipped vectors is real weight to carry. Revisit when this
 * array is in the hundreds, or when misses start showing up in analytics.
 */
export const searchIndex = [
  // Pages
  {
    id: "dashboard",
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboard,
    group: "pages",
    keywords: ["home", "stats", "overview", "analytics"],
  },
  {
    id: "installation",
    title: "Installation",
    url: "/installation",
    icon: Briefcase,
    group: "pages",
    keywords: ["setup", "install", "embed", "getting started"],
  },
  {
    id: "installation-website",
    title: "Website Integration",
    url: "/installation/website-integration",
    icon: Code,
    group: "pages",
    section: "Installation",
    keywords: ["script tag", "embed", "snippet", "widget"],
  },
  {
    id: "installation-sdk",
    title: "SDK Advanced",
    url: "/installation/sdk-advanced",
    icon: Code,
    group: "pages",
    section: "Installation",
    keywords: ["javascript", "api", "developer", "sdk"],
  },
  {
    id: "chat-history",
    title: "Chat History",
    url: "/chat-history",
    icon: MessageSquare,
    group: "pages",
    keywords: [
      "conversations",
      "transcripts",
      "messages",
      "logs",
      "past chats",
      "what users asked",
      "history",
      "archive",
      "read chats",
    ],
  },
  {
    id: "leads",
    title: "Leads",
    url: "/leads",
    icon: BookUser,
    group: "pages",
    keywords: [
      "contacts",
      "customers",
      "emails",
      "captured",
      "phone numbers",
      "export",
      "csv",
      "signups",
      "enquiries",
      "prospects",
    ],
  },
  {
    id: "leads-human-support",
    title: "Human Support",
    url: "/leads",
    tab: "human-settings",
    icon: Headset,
    group: "pages",
    section: "Leads",
    keywords: [
      "live agent",
      "handoff",
      "escalation",
      "takeover",
      "talk to human",
      "real person",
      "support team",
      "transfer",
      "operator",
    ],
  },

  // Knowledge Base
  {
    id: "custom-responses",
    title: "Custom Responses",
    url: "/custom-responses",
    icon: MessageSquareText,
    group: "knowledge",
    keywords: ["answers", "faq", "canned", "replies"],
  },
  {
    id: "text-snippets",
    title: "Text Snippets",
    url: "/text-snippets",
    icon: Type,
    group: "knowledge",
    keywords: ["content", "training data", "text", "paste"],
  },
  {
    id: "website-links",
    title: "Website Links",
    url: "/website-links",
    icon: Link2,
    group: "knowledge",
    keywords: [
      "urls",
      "crawl",
      "scrape",
      "pages",
      "sitemap",
      "add website",
      "index site",
      "fetch pages",
      "domain",
    ],
  },
  {
    id: "website-files",
    title: "Files & Data Sources",
    url: "/website-files",
    icon: FileText,
    group: "knowledge",
    keywords: [
      "upload",
      "pdf",
      "docs",
      "documents",
      "sources",
      "csv",
      "excel",
      "word",
      "txt",
      "attach",
      "knowledge base",
      "train",
      "add data",
      "google",
      "confluence",
      "dropbox",
      "github",
      "notion",
      "gitbook",
      "slack",
      "zapier",
      "salesforce",
      "onedrive",
      "sharepoint",
      "google drive",
      "facebook",
      "messenger",
      "instagram",
      "integration",
      "integrations",
    ],
  },
  {
    id: "auto-sync",
    title: "Auto Sync Jobs",
    url: "/auto-sync",
    icon: History,
    group: "knowledge",
    keywords: [
      "schedule",
      "recrawl",
      "refresh",
      "automatic",
      "jobs",
      "cron",
      "keep up to date",
      "sync",
      "stale content",
      "re-index",
    ],
  },

  // Customizations
  {
    id: "conversation-starters",
    title: "Conversation Starters",
    url: "/conversation-starters",
    icon: HelpCircle,
    group: "customizations",
    keywords: ["suggestions", "prompts", "quick replies", "openers"],
  },
  {
    id: "conversation-followups",
    title: "Conversation Followups",
    url: "/conversation-followups",
    icon: Reply,
    group: "customizations",
    keywords: ["follow up", "suggested questions", "next steps"],
  },
  {
    id: "appearance",
    title: "Appearance",
    url: "/appearance",
    icon: Palette,
    group: "customizations",
    keywords: [
      "theme",
      "colors",
      "branding",
      "look",
      "style",
      "widget design",
      "dark mode",
      "light mode",
      "logo",
      "avatar",
      "font",
      "customize",
      "position",
      "bubble",
    ],
  },

  // Settings (tab deep links)
  {
    id: "settings",
    title: "Settings",
    url: "/settings",
    icon: Settings,
    group: "settings",
    keywords: ["configuration", "preferences", "options"],
  },
  {
    id: "settings-instructions",
    title: "Chatbot Instructions",
    url: "/settings",
    tab: "instructions",
    icon: Sparkles,
    group: "settings",
    section: "Settings",
    keywords: [
      "prompt",
      "system prompt",
      "behaviour",
      "behavior",
      "rules",
      "tone",
      "training",
      "guardrails",
      "restrict",
      "what it can say",
      "custom instructions",
    ],
  },
  {
    id: "settings-personas",
    title: "Chatbot Persona",
    url: "/settings",
    tab: "personas",
    icon: UserCircle,
    group: "settings",
    section: "Settings",
    keywords: ["personality", "character", "voice", "role"],
  },
  {
    id: "settings-localization",
    title: "Language & Region",
    url: "/settings",
    tab: "localization",
    icon: Globe,
    group: "settings",
    section: "Settings",
    keywords: ["language", "locale", "translation", "timezone", "region"],
  },
  {
    id: "settings-general",
    title: "General Settings",
    url: "/settings",
    tab: "general",
    icon: Settings,
    group: "settings",
    section: "Settings",
    keywords: [
      "name",
      "rename",
      "delete chatbot",
      "basics",
      "remove",
      "destroy",
      "title",
      "danger zone",
    ],
  },
  {
    id: "settings-chat-modes",
    title: "Chat Modes",
    url: "/settings",
    tab: "chat-modes",
    icon: MessagesSquare,
    group: "settings",
    section: "Settings",
    keywords: ["mode", "strict", "creative", "answering"],
  },
  {
    id: "settings-user-data",
    title: "User Data",
    url: "/settings",
    tab: "user-data",
    icon: Database,
    group: "settings",
    section: "Settings",
    keywords: ["collect", "fields", "form", "capture", "privacy"],
  },

  // Advanced
  {
    id: "chatbot-members",
    title: "Chatbot Members",
    url: "/chatbot-members",
    icon: Users,
    group: "advanced",
    keywords: ["team", "invite", "permissions", "roles", "collaborators"],
  },
  {
    id: "account-members",
    title: "Account Members",
    url: "/account-members",
    icon: Users,
    group: "advanced",
    keywords: ["team", "invite", "permissions", "roles", "organization"],
  },
  {
    id: "referral",
    title: "Referral",
    url: "/referral",
    icon: UserStar,
    group: "advanced",
    keywords: ["invite", "affiliate", "rewards"],
  },
  {
    id: "integrations",
    title: "Integrations",
    url: "/integrations",
    icon: Plug,
    group: "advanced",
    keywords: [
      "connect",
      "apps",
      "slack",
      "third party",
      "zapier",
      "crisp",
      "zendesk",
      "freshdesk",
      "slack",
      "intercom",
      "hubspot",
      "zohosalesiq",
      "hubspot",
      "whatsapp",
      "sync with",
      "facebook",
      "instagram",
      "messenger",
      "integration",
    ],
  },
  {
    id: "webhooks",
    title: "Webhooks",
    url: "/webhooks",
    icon: Zap,
    group: "advanced",
    keywords: [
      "events",
      "callbacks",
      "http",
      "notifications",
      "post to my server",
      "endpoint",
      "payload",
      "subscribe",
      "trigger",
    ],
  },

  // Account
  {
    id: "account",
    title: "Account",
    url: "/account",
    icon: BadgeCheck,
    group: "account",
    keywords: ["profile", "password", "email", "me"],
  },
  {
    id: "billing",
    title: "Billing",
    url: "/billing",
    icon: CreditCard,
    group: "account",
    keywords: [
      "payment",
      "invoice",
      "subscription",
      "plan",
      "card",
      "cancel",
      "upgrade",
      "downgrade",
      "receipt",
      "pricing",
      "refund",
      "renew",
    ],
  },
  {
    id: "billing-addons",
    title: "Add-ons",
    url: "/billing",
    tab: "addons",
    icon: CreditCard,
    group: "account",
    section: "Billing",
    keywords: ["extras", "upgrade", "credits", "quota"],
  },
  {
    id: "usage",
    title: "Usage",
    url: "/usage",
    icon: ChartLine,
    group: "account",
    keywords: [
      "credits",
      "quota",
      "limits",
      "consumption",
      "metrics",
      "how many messages",
      "running out",
      "remaining",
      "spend",
      "tokens used",
    ],
  },
  {
    id: "usage-api-keys",
    title: "API Keys",
    url: "/usage/api-keys",
    icon: Key,
    group: "account",
    section: "Usage",
    keywords: [
      "token",
      "secret",
      "credentials",
      "api",
      "generate key",
      "revoke",
      "bearer",
      "auth",
      "developer access",
    ],
  },

  // SDK Advanced sections — these ids exist in the SECTIONS array on the page,
  // and that page calls useHashScroll(), so the #anchor actually resolves.
  {
    id: "sdk-widget-visibility",
    title: "Widget Visibility",
    url: "/installation/sdk-advanced",
    hash: "widget-visibility",
    icon: Eye,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["show", "hide", "open", "close", "toggle widget"],
  },
  {
    id: "sdk-send-messages",
    title: "Send Messages",
    url: "/installation/sdk-advanced",
    hash: "send-messages",
    icon: MessageSquare,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["sendMessage", "programmatic", "trigger message"],
  },
  {
    id: "sdk-conversation-reset",
    title: "Reset Conversation",
    url: "/installation/sdk-advanced",
    hash: "conversation-reset",
    icon: RotateCcw,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["clear", "restart", "new chat", "reset"],
  },
  {
    id: "sdk-widget-reload",
    title: "Reload Widget",
    url: "/installation/sdk-advanced",
    hash: "widget-reload",
    icon: RefreshCw,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["refresh", "reinit", "remount"],
  },
  {
    id: "sdk-user-session",
    title: "User Sessions",
    url: "/installation/sdk-advanced",
    hash: "user-session",
    icon: UserCircle,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["identify", "login", "user id", "session"],
  },
  {
    id: "sdk-context",
    title: "Chatbot Context",
    url: "/installation/sdk-advanced",
    hash: "context",
    icon: Code,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["setContext", "metadata", "custom data", "variables"],
  },
  {
    id: "sdk-custom-css",
    title: "Custom CSS",
    url: "/installation/sdk-advanced",
    hash: "custom-css",
    icon: Palette,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["styling", "override", "css", "theme"],
  },
  {
    id: "sdk-hidebtn",
    title: "hideButton Mode",
    url: "/installation/sdk-advanced",
    hash: "hidebtn",
    icon: EyeOff,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["hide button", "launcher", "custom trigger"],
  },
  {
    id: "sdk-container-mode",
    title: "Container Mode",
    url: "/installation/sdk-advanced",
    hash: "container-mode",
    icon: Boxes,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["inline", "embed in div", "container"],
  },
  {
    id: "sdk-multi-widget",
    title: "Multiple Widgets",
    url: "/installation/sdk-advanced",
    hash: "multi-widget",
    icon: Layers,
    group: "sdk",
    section: "SDK Advanced",
    keywords: ["multiple", "several", "many widgets"],
  },
];

/**
 * Valid ?tab= values per route, used only for a dev-time warning.
 * Mirrors VALID_TABS in settings/page.jsx and the tab list in billing/leads.
 */
const VALID_TABS_BY_ROUTE = {
  "/settings": [
    "general",
    "user-data",
    "chat-modes",
    "localization",
    "personas",
    "instructions",
  ],
  "/billing": ["addons"],
  "/leads": ["human-settings"],
};

/** Resolve an index entry into a routable href. */
export function buildHref(entry) {
  let href = entry.url;
  if (entry.tab) href += `?tab=${encodeURIComponent(entry.tab)}`;
  if (entry.hash) href += `#${entry.hash}`;
  return href;
}

// Dev-only sanity check: a typo'd tab silently falls back to the default tab
// with no error at runtime, which is painful to notice. Warn loudly instead.
if (process.env.NODE_ENV === "development") {
  for (const entry of searchIndex) {
    if (!entry.tab) continue;
    const valid = VALID_TABS_BY_ROUTE[entry.url];
    if (valid && !valid.includes(entry.tab)) {
      console.warn(
        `[search-index] Entry "${entry.id}" has tab "${entry.tab}" which is not valid for ${entry.url}. Expected one of: ${valid.join(", ")}`,
      );
    }
  }
}
