"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "SharePoint";

const FAQS = [
  {
    question: "How do I connect SharePoint with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose SharePoint, authorize securely via 1-click OAuth with your Microsoft 365 account, and select the sites or document libraries you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What SharePoint content can ContextGPT read?",
    answer:
      "ContextGPT can index SharePoint sites, document libraries, internal wikis, and policy documents, turning them into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit SharePoint content?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in SharePoint.",
  },
  {
    question: "Is my SharePoint data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Microsoft OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your internal content is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the SharePoint integration included in the free trial?",
    answer:
      "Yes! SharePoint is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select SharePoint under Data Sources",
  "Authenticate securely using 1-click Microsoft 365 OAuth",
  "Select the specific sites or document libraries to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a page or document in SharePoint, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Site Context",
    description:
      "Native parsing for SharePoint sites, document libraries, internal wikis, and policy documents.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which SharePoint sites or libraries ContextGPT can access. Keep sensitive internal content private while publishing shared knowledge.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact SharePoint records.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Microsoft 365 OAuth authorization. Your SharePoint data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your SharePoint data, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in SharePoint,",
    rest: " scattered across sites, libraries, and wikis no visitor can search",
    chatMessage: "Why is having answers buried in SharePoint a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Employees ask questions your team answers manually,",
    rest: " digging through the same policy page or document library over and over",
    chatMessage: "How can ContextGPT stop my team from manually digging through SharePoint to answer questions?",
  },
  {
    bold: "SharePoint content changes constantly,",
    rest: " but your intranet and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my SharePoint content changes?",
  },
  {
    bold: "A slow answer loses the moment,",
    rest: " even when the correct information was sitting in your SharePoint the whole time",
    chatMessage: "How does ContextGPT turn my SharePoint content into instant answers so I stop losing time?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect SharePoint and train your AI straight from your existing sites and libraries",
    chatMessage: "How can I get ContextGPT set up with SharePoint in just 5 minutes?",
  },
  {
    bold: "Turn SharePoint into instant answers:",
    rest: " every site, library, and wiki becomes something people can actually query",
    chatMessage: "How does ContextGPT turn my SharePoint content into instant answers?",
  },
  {
    bold: "Support your organization around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your SharePoint",
    chatMessage: "How can ContextGPT support my organization 24/7 using my SharePoint content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a page or document in SharePoint and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in SharePoint?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the SharePoint sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="SharePoint ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every site, document library, and wiki inside SharePoint into an intelligent, self-learning AI chatbot. Automatically sync organizational knowledge and answer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">SharePoint</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            internal sites and documents. <span className="whitespace-nowrap">Good news</span> —
            you&apos;ve landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your SharePoint, we ingest your sites, document
            libraries, and internal wikis, and turn them into a searchable knowledge base your chatbot
            can actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual SharePoint content
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              OneDrive
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Confluence
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Notion
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing time right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to keep someone engaged</strong> if you answer within 5
          minutes — but most organizations take hours digging through SharePoint.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect SharePoint with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual policy re-explaining. Turn your existing SharePoint content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
