"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Zoho SalesIQ";

const FAQS = [
  {
    question: "How do I connect Zoho SalesIQ with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Deploy Channels, choose Zoho SalesIQ, authorize securely via 1-click OAuth, and connect your SalesIQ widget. Your trained chatbot goes live in your chat window automatically.",
  },
  {
    question: "Does Zoho SalesIQ act as a data source or a deployment channel?",
    answer:
      "Zoho SalesIQ is a deployment channel. ContextGPT responds inside your SalesIQ widget using the knowledge base you've already trained from your help center, documents, or CRM.",
  },
  {
    question: "Can the chatbot handle both sales and support questions in SalesIQ?",
    answer:
      "Yes! ContextGPT can answer both pre-sales product questions and general support questions using the same trained knowledge base, right inside your SalesIQ widget.",
  },
  {
    question: "Can I still route qualified leads to my sales team?",
    answer:
      "Absolutely. You can configure escalation rules so qualified conversations are handed off from ContextGPT to your sales team within Zoho SalesIQ whenever a human touch is needed.",
  },
  {
    question: "Is the Zoho SalesIQ integration included in the free trial?",
    answer:
      "Yes! Zoho SalesIQ is available as a core deployment channel across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Zoho SalesIQ under Deploy Channels",
  "Authenticate securely using 1-click Zoho OAuth",
  "Connect ContextGPT to your existing SalesIQ chat widget",
  "Customize greetings, tone, and escalation rules for handing off to your sales team",
  "Go live and start greeting website visitors with instant, trained answers",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update your knowledge base anywhere, hit resync, and your SalesIQ widget instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Visitor Context",
    description:
      "Native support for product FAQs, pricing details, and support articles, so visitors get relevant answers the moment they open the widget.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly what knowledge ContextGPT can share through SalesIQ. Keep internal pricing notes private while publishing public product info.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so your sales team can verify answers against your exact source records.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Zoho OAuth authorization. Visitor conversation data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained, deploy the same chatbot to your Website, Zoho SalesIQ, Slack, WhatsApp, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers never reach the visitor,",
    rest: " because no one is watching the Zoho SalesIQ widget the moment they land on your site",
    chatMessage: "Why do website visitors leave before getting answers in Zoho SalesIQ, and how does ContextGPT fix that?",
  },
  {
    bold: "Visitors ask questions your team answers manually,",
    rest: " typing the same pricing or product reply over and over inside SalesIQ",
    chatMessage: "How can ContextGPT stop my team from manually typing the same answers in Zoho SalesIQ?",
  },
  {
    bold: "Your product and pricing change constantly,",
    rest: " but your SalesIQ widget keeps giving visitors outdated answers",
    chatMessage: "How does ContextGPT make sure my Zoho SalesIQ answers stay accurate as my product changes?",
  },
  {
    bold: "A slow reply loses the lead,",
    rest: " even when the right answer was one click away in your Zoho SalesIQ widget",
    chatMessage: "How does ContextGPT turn my Zoho SalesIQ widget into instant answers so I stop losing leads?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Zoho SalesIQ and greet visitors with your AI trained on what you already know",
    chatMessage: "How can I get ContextGPT set up with Zoho SalesIQ in just 5 minutes?",
  },
  {
    bold: "Turn every visit into instant answers:",
    rest: " product questions, pricing questions, and support questions handled the moment they arrive",
    chatMessage: "How does ContextGPT turn my Zoho SalesIQ widget into instant answers for visitors?",
  },
  {
    bold: "Capture leads around the clock:",
    rest: " even when your sales team is busy, offline, or asleep, your SalesIQ widget keeps working",
    chatMessage: "How can ContextGPT capture leads for my business 24/7 using Zoho SalesIQ?",
  },
  {
    bold: "Always up to date:",
    rest: " update your knowledge base once and every conversation in Zoho SalesIQ reflects it instantly",
    chatMessage: "How does ContextGPT keep answers in sync across my Zoho SalesIQ widget?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Zoho SalesIQ connection?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language conversations?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Zoho SalesIQ ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Deploy an intelligent, self-learning AI chatbot straight inside your Zoho SalesIQ widget. Greet website visitors, answer sales and support questions instantly, and hand off qualified leads with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Zoho SalesIQ</span> to ChatGPT or maybe
            Gemini or Claude or maybe some other LLMs, and get real answers delivered straight through
            your website chat widget. <span className="whitespace-nowrap">Good news</span> —
            you&apos;ve landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You train us on your product info, pricing, and support content, we
            deploy it straight into your Zoho SalesIQ widget, and turn every visitor conversation into
            something your AI can actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual trained knowledge base
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is also on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              WhatsApp
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Messenger
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing leads right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a lead</strong> if you respond within 5
          minutes — but most sales teams take hours.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Zoho SalesIQ with ChatGPT?"
      featuresSubheading="Eliminate slow manual replies and missed website visitors. Deploy an automated AI agent straight inside the SalesIQ widget you already use."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
