"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Google Chat";

const FAQS = [
  {
    question: "How do I connect Google Chat with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Deploy Channels, choose Google Chat, authorize securely via 1-click OAuth, and select the spaces you want your chatbot deployed into. Setup takes just a few minutes.",
  },
  {
    question: "What knowledge does the chatbot use inside Google Chat?",
    answer:
      "The chatbot answers inside Google Chat using the same knowledge base you've already built in ContextGPT from your docs, tickets, and internal content, so no separate training is needed.",
  },
  {
    question: "Will the chatbot update automatically when my knowledge base changes?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's answers inside Google Chat always reflect the newest content.",
  },
  {
    question: "Is my Google Workspace data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Google OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your Workspace data is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the Google Chat integration included in the free trial?",
    answer:
      "Yes! Google Chat is available as a core deployment channel across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Google Chat under Deploy Channels",
  "Authenticate securely using 1-click Google Workspace OAuth",
  "Select the specific Google Chat spaces where the chatbot should be added",
  "Let ContextGPT connect your existing knowledge base to the chat surface",
  "Start answering teammate questions instantly inside Google Chat",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a doc or ticket in your knowledge base, hit resync, and your chatbot instantly answers with the newest info inside Google Chat without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Workspace Context",
    description:
      "Native parsing for team conversations, shared docs, and internal knowledge already connected to your ContextGPT workspace.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which Google Chat spaces ContextGPT can join. Keep sensitive channels private while enabling public-facing spaces.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so teammates can verify answers against your exact source records.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Google Workspace OAuth authorization. Your data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your content, deploy your chatbot to Google Chat, Slack, WhatsApp, Zendesk, or a custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in scattered docs,",
    rest: " and teammates keep pinging each other in Google Chat instead of finding them",
    chatMessage: "Why is having answers scattered a problem, and how does ContextGPT fix that inside Google Chat?",
  },
  {
    bold: "Teammates ask questions your team answers manually,",
    rest: " retyping the same explanation in a Google Chat thread over and over",
    chatMessage: "How can ContextGPT stop my team from manually retyping answers in Google Chat?",
  },
  {
    bold: "Internal knowledge changes constantly,",
    rest: " but the answers people get in Google Chat quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my internal content changes?",
  },
  {
    bold: "A slow answer stalls the whole team,",
    rest: " even when the correct information already existed somewhere in your workspace",
    chatMessage: "How does ContextGPT turn my workspace content into instant answers inside Google Chat?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Google Chat and deploy your AI straight from your existing knowledge base",
    chatMessage: "How can I get ContextGPT set up with Google Chat in just 5 minutes?",
  },
  {
    bold: "Turn every question into an instant answer:",
    rest: " teammates get accurate replies right inside the Google Chat spaces they already use",
    chatMessage: "How does ContextGPT turn team questions into instant answers inside Google Chat?",
  },
  {
    bold: "Support your team around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your knowledge base",
    chatMessage: "How can ContextGPT support my team 24/7 inside Google Chat?",
  },
  {
    bold: "Always up to date:",
    rest: " update your source content and your chatbot's answers inside Google Chat update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync inside Google Chat?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Google Chat integration?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Google Chat ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Deploy your ContextGPT chatbot directly inside Google Chat so your Workspace team gets instant, accurate answers without ever leaving a conversation, backed by verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Google Chat</span> to ChatGPT or maybe
            Gemini or Claude or maybe some other LLMs, and get real answers pulled straight from your
            own team knowledge. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your workspace content, we ingest your docs, tickets, and
            internal notes, and turn them into a searchable knowledge base your chatbot can actually
            reason over, right inside Google Chat. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual workspace data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why your team is stuck waiting on answers"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to keep momentum</strong> if a question gets answered
          within 5 minutes — but most teams take hours to respond in Google Chat.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Google Chat with ChatGPT?"
      featuresSubheading="Eliminate repeated internal questions and manual answer re-writing. Turn your existing knowledge base straight into an automated AI teammate inside Google Chat."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
