"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "GitHub";

const FAQS = [
  {
    question: "How do I connect GitHub with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose GitHub, authorize securely via 1-click OAuth, and select the repositories (README files, wikis, issues) you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What GitHub data can ContextGPT read?",
    answer:
      "ContextGPT can index your README files, repository wikis, markdown documentation, and issue threads, turning them into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit GitHub content?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in GitHub.",
  },
  {
    question: "Is my GitHub data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official GitHub OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your repository data is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the GitHub integration included in the free trial?",
    answer:
      "Yes! GitHub is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select GitHub under Data Sources",
  "Authenticate securely using 1-click GitHub OAuth",
  "Select the specific repositories (READMEs, wikis, issues) to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or developer portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a README or wiki page in GitHub, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Repository Context",
    description:
      "Native parsing for README files, wikis, markdown docs, and issue threads across your repositories.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which repositories ContextGPT can access. Keep private codebases untouched while publishing public docs.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact GitHub files.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure GitHub OAuth authorization. Your repository data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your GitHub content, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in GitHub,",
    rest: " scattered across READMEs, wikis, and issue threads no developer wants to dig through",
    chatMessage: "Why is having answers buried in GitHub a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Developers ask questions your docs already answer,",
    rest: " and your team ends up copy-pasting the same wiki reply or README section over and over",
    chatMessage: "How can ContextGPT stop my team from manually copy-pasting GitHub content to answer developers?",
  },
  {
    bold: "GitHub content changes constantly,",
    rest: " but your setup guides and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my GitHub content changes?",
  },
  {
    bold: "A slow answer loses the contributor,",
    rest: " even when the correct information was sitting in your GitHub the whole time",
    chatMessage: "How does ContextGPT turn my GitHub content into instant answers so I stop losing contributors?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect GitHub and train your AI straight from your existing READMEs and wikis",
    chatMessage: "How can I get ContextGPT set up with GitHub in just 5 minutes?",
  },
  {
    bold: "Turn GitHub into instant answers:",
    rest: " every README, wiki page, and issue thread becomes something developers can actually query",
    chatMessage: "How does ContextGPT turn my GitHub content into instant answers for developers?",
  },
  {
    bold: "Support developers around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your GitHub",
    chatMessage: "How can ContextGPT support developers 24/7 using my GitHub content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a README or wiki in GitHub and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in GitHub?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the GitHub sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="GitHub ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every README, wiki page, and issue thread inside GitHub into an intelligent, self-learning AI chatbot. Automatically sync your repository knowledge and answer developer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">GitHub</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            repositories. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your GitHub, we ingest your README files, wikis, and
            issue threads, and turn them into a searchable knowledge base your chatbot can actually
            reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual GitHub data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing developers right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to keep a contributor</strong> if you answer within 5
          minutes — but most projects take hours to respond in issues.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect GitHub with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual issue re-writing. Turn your existing GitHub content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
