"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "WhatsApp";

const FAQS = [
  {
    question: "How do I connect ChatGPT / ContextGPT to WhatsApp?",
    answer:
      "WhatsApp Business is launching soon as a deployment channel. From your ContextGPT dashboard's Deploy Channels section, join the waitlist and you'll be notified the moment you can connect your WhatsApp Business account.",
  },
  {
    question: "Is the WhatsApp integration available today?",
    answer:
      "Not yet. It is currently in development and marked as coming soon in the ContextGPT deployment channels list, so you can join the waitlist now to be first in line.",
  },
  {
    question: "Will my WhatsApp chatbot use the same knowledge base as my other channels?",
    answer:
      "Yes! Once launched, your WhatsApp deployment will use the exact same trained knowledge base you already use across your website, Slack, and other deployment channels, no retraining required.",
  },
  {
    question: "Will the WhatsApp bot hand off to a human agent when needed?",
    answer:
      "Yes, the WhatsApp deployment is being built with escalation rules so conversations can hand off to a human agent whenever the chatbot can't confidently answer.",
  },
  {
    question: "Is the WhatsApp integration included in the free trial?",
    answer:
      "Pricing details will be shared closer to launch. In the meantime, you can explore every other ContextGPT deployment channel during your 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and join the waitlist under Deploy Channels for WhatsApp",
  "Get notified the moment WhatsApp Business support goes live",
  "Connect your WhatsApp Business account with 1-click OAuth once available",
  "Configure the chatbot's responses, tone, and escalation rules",
  "Go live and start answering customers directly on WhatsApp",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update your knowledge base anywhere, hit resync, and your WhatsApp chatbot will instantly answer with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Same Trained Knowledge, New Channel",
    description:
      "WhatsApp will reuse the exact same trained knowledge base you already built, no separate content setup required.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly what your WhatsApp chatbot can answer and when it should escalate, keeping sensitive conversations handled by your team.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so customers on WhatsApp can trust the answers they receive.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure WhatsApp Business OAuth authorization. Your conversations are encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API, all from the same knowledge base.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your customers are already messaging you on WhatsApp,",
    rest: " but no one's answering fast enough when your team is offline",
    chatMessage: "Why is slow WhatsApp response time a problem, and how will ContextGPT fix that?",
  },
  {
    bold: "Your team answers the same WhatsApp questions manually,",
    rest: " retyping the same reply to different customers over and over",
    chatMessage: "How can ContextGPT stop my team from manually retyping WhatsApp answers?",
  },
  {
    bold: "WhatsApp is the first place customers reach out in many regions,",
    rest: " but you have no automated way to meet them there yet",
    chatMessage: "How will ContextGPT help me meet customers where they already are, on WhatsApp?",
  },
  {
    bold: "A slow reply loses the customer,",
    rest: " even when the correct answer was already sitting in your knowledge base",
    chatMessage: "How will ContextGPT turn my knowledge base into instant WhatsApp answers so I stop losing customers?",
  },
];

const benefits = [
  {
    bold: "Launch in minutes once live:",
    rest: " connect WhatsApp Business and your existing trained knowledge base goes to work immediately",
    chatMessage: "How quickly will I be able to set up ContextGPT on WhatsApp once it launches?",
  },
  {
    bold: "Turn your knowledge base into instant WhatsApp answers:",
    rest: " every doc, ticket, and page you've already trained on becomes something customers can query on WhatsApp",
    chatMessage: "How will ContextGPT turn my knowledge base into instant WhatsApp answers?",
  },
  {
    bold: "Support customers around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what you've already trained ContextGPT on",
    chatMessage: "How will ContextGPT support my customers 24/7 on WhatsApp?",
  },
  {
    bold: "Always up to date:",
    rest: " update your knowledge base once and your WhatsApp chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep WhatsApp answers in sync when I update my knowledge base?",
  },
];

const microBar = [
  { text: "Launching soon", msg: "When is the WhatsApp integration launching?" },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure will the WhatsApp connection be?" },
  { text: "Same Knowledge Base, Every Channel", msg: "Will WhatsApp use the same knowledge base as my other channels?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language conversations?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="WhatsApp ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Deploy your trained AI chatbot directly on WhatsApp Business, launching soon, and bring instant, self-learning answers to the world's most used messaging app with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to bring{" "}
            <span className="font-semibold text-[#155ded]">ChatGPT-powered answers</span> to
            WhatsApp, the app your customers already have open all day, every day.{" "}
            <span className="whitespace-nowrap">Good news</span> — you&apos;ve landed in the right
            place, and this one&apos;s launching soon.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we're building exactly
            this kind of deployment. You train your chatbot once on your existing docs, tickets, and
            pages, and once WhatsApp Business support goes live, that same knowledge base answers
            customers right inside their WhatsApp chats. <br />
            No separate content setup, using Auto-Synchronization your WhatsApp chatbot stays as
            current as every other channel you deploy to.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual trained knowledge base
            </span>
            , not a guess. If you&apos;ve been putting off setting up an AI-powered WhatsApp presence
            because it sounded complicated, it won&apos;t be.{" "}
            <span className="font-semibold text-slate-900">Join the waitlist</span> and you&apos;ll be
            first to know when it&apos;s live.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that while you wait for WhatsApp, your team can already be live on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              HubSpot
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              your website
            </span>{" "}
            or maybe some other place, you can straight away connect those into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations and deployment channels.
          </>
        ),
      }}
      problemsHeading="Why you're losing customers right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a customer</strong> if you respond within 5
          minutes — but most businesses take hours to reply on WhatsApp.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect ChatGPT to WhatsApp?"
      featuresSubheading="Eliminate slow replies and manual copy-pasting. Turn your existing trained knowledge base straight into an automated AI agent on WhatsApp."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
