"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Zendesk";

const FAQS = [
  {
    question: "How do I connect Zendesk with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose Zendesk, authorize securely via 1-click OAuth, and select the help center articles and tickets you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What Zendesk data can ContextGPT read?",
    answer:
      "ContextGPT can index your Zendesk Help Center articles and resolved support tickets, turning them into a searchable knowledge base your chatbot can actually reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit Zendesk content?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in Zendesk.",
  },
  {
    question: "Is my Zendesk data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Zendesk OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your support data is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the Zendesk integration included in the free trial?",
    answer:
      "Yes! Zendesk is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Zendesk under Data Sources",
  "Authenticate securely using 1-click Zendesk OAuth",
  "Select the specific Zendesk objects (help center articles, resolved tickets) to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a help center article or close out a ticket in Zendesk, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Help Desk Context",
    description:
      "Native parsing for Zendesk Help Center articles and resolved support tickets, so nothing your team already wrote goes to waste.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which Zendesk content ContextGPT can access. Keep internal ticket notes private while publishing public help articles.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact Zendesk records.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Zendesk OAuth authorization. Your support data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your Zendesk data, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk Chat widget, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in Zendesk,",
    rest: " scattered across help center articles and closed tickets no visitor can search",
    chatMessage: "Why is having answers buried in Zendesk a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Customers ask questions your team answers manually,",
    rest: " copy-pasting the same ticket reply or help center article over and over",
    chatMessage: "How can ContextGPT stop my team from manually copy-pasting Zendesk content to answer customers?",
  },
  {
    bold: "Zendesk content changes constantly,",
    rest: " but your website and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my Zendesk content changes?",
  },
  {
    bold: "A slow answer loses the customer,",
    rest: " even when the correct information was sitting in your Zendesk the whole time",
    chatMessage: "How does ContextGPT turn my Zendesk content into instant answers so I stop losing customers?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Zendesk and train your AI straight from your existing help center and resolved tickets",
    chatMessage: "How can I get ContextGPT set up with Zendesk in just 5 minutes?",
  },
  {
    bold: "Turn Zendesk into instant answers:",
    rest: " every article and ticket resolution becomes something customers can actually query",
    chatMessage: "How does ContextGPT turn my Zendesk content into instant answers for customers?",
  },
  {
    bold: "Cut routine ticket volume:",
    rest: " let the chatbot resolve repeat questions automatically before they ever hit your queue",
    chatMessage: "How can ContextGPT reduce the number of tickets landing in my Zendesk queue?",
  },
  {
    bold: "Always up to date:",
    rest: " edit an article or resolve a ticket in Zendesk and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in Zendesk?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Zendesk sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Zendesk ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every help center article and resolved ticket inside Zendesk into an intelligent, self-learning AI chatbot. Automatically sync support knowledge and answer customer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Zendesk</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            support data. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your Zendesk, we ingest your help center articles and
            resolved tickets, and turn them into a searchable knowledge base your chatbot can
            actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual Zendesk data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              HubSpot
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing customers right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to retain a customer</strong> if you respond within 5
          minutes — but most support teams take hours.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Zendesk with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual ticket re-writing. Turn your existing Zendesk content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
