"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "OneDrive";

const FAQS = [
  {
    question: "How do I connect OneDrive with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose OneDrive, authorize securely via 1-click OAuth with your Microsoft account, and select the folders or files you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What OneDrive files can ContextGPT read?",
    answer:
      "ContextGPT can index Word documents, Excel spreadsheets, PowerPoint presentations, and PDFs stored in OneDrive, turning them into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit a file in OneDrive?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in OneDrive.",
  },
  {
    question: "Is my OneDrive data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Microsoft OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your files are never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the OneDrive integration included in the free trial?",
    answer:
      "Yes! OneDrive is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select OneDrive under Data Sources",
  "Authenticate securely using 1-click Microsoft OAuth",
  "Select the specific folders or files to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a document in OneDrive, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Document Context",
    description:
      "Native parsing for Word, Excel, PowerPoint, and PDF files stored across your OneDrive folders.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which OneDrive folders or files ContextGPT can access. Keep sensitive files private while publishing shared documents.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact OneDrive files.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Microsoft OAuth authorization. Your OneDrive data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your OneDrive data, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in OneDrive,",
    rest: " scattered across folders and files no visitor can search",
    chatMessage: "Why is having answers buried in OneDrive a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Teammates ask questions your team answers manually,",
    rest: " digging through the same shared document over and over",
    chatMessage: "How can ContextGPT stop my team from manually digging through OneDrive to answer questions?",
  },
  {
    bold: "OneDrive content changes constantly,",
    rest: " but your website and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my OneDrive content changes?",
  },
  {
    bold: "A slow answer loses the moment,",
    rest: " even when the correct information was sitting in your OneDrive the whole time",
    chatMessage: "How does ContextGPT turn my OneDrive content into instant answers so I stop losing time?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect OneDrive and train your AI straight from your existing documents",
    chatMessage: "How can I get ContextGPT set up with OneDrive in just 5 minutes?",
  },
  {
    bold: "Turn OneDrive into instant answers:",
    rest: " every document, sheet, and deck becomes something people can actually query",
    chatMessage: "How does ContextGPT turn my OneDrive content into instant answers?",
  },
  {
    bold: "Support your team around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your OneDrive",
    chatMessage: "How can ContextGPT support my team 24/7 using my OneDrive content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a file in OneDrive and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in OneDrive?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the OneDrive sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="OneDrive ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every document, spreadsheet, and presentation inside OneDrive into an intelligent, self-learning AI chatbot. Automatically sync team knowledge and answer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">OneDrive</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            documents. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your OneDrive, we ingest your Word docs, Excel sheets,
            and PowerPoint decks, and turn them into a searchable knowledge base your chatbot can
            actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual OneDrive files
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              SharePoint
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Google Drive
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              HubSpot
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing time right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to keep someone engaged</strong> if you answer within 5
          minutes — but most teams take hours digging through OneDrive.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect OneDrive with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual file hunting. Turn your existing OneDrive content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
