import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern";
import { cn } from "@/lib/utils";
import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | ContextGPT",
};

export default function Privacy() {
  return (
    <div className="bg-white">
      <div className="bg-linear-to-b from-indigo-50/70 to-white py-4 sm:py-8 md-py--16 px-4 sm:px-6 lg:px-4">
        <AnimatedGridPattern
            numSquares={10}
            maxOpacity={0.1}
            duration={2}
            repeatDelay={1}
            height={180}
            width={180}
            className={cn(
              "mask-[radial-gradient(500px_circle_at_center,white,transparent)]",
              "inset-x-0 inset-y-[-20%] h-[100%] "
            )}
          />
          {/* Hero */}
        <div className="p-[8rem] flex justify-center items-center flex-col gap-4 ">
          <p className="text-center text-sm font-bold text-blue-600">Privacy Policy</p>
          <h1 className="text-center text-6xl">Privacy Policy</h1>
          <p className="text-center text-xl pt-4 text-gray-500">
            By continuing to use our platform, you agree that you read the privacy policy.
          </p>
        </div>
      </div>
      <article className="prose prose-slate mx-auto max-w-3xl px-8">

        <h2>Introduction</h2>
        <p>
          ContextGPT, operated by Krishna Gupta and our team (&ldquo;Company&rdquo;,
          &ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates
          <Link href="http://contextgpt.in" className="text-black underline">https://contextgpt.in</Link> (hereinafter referred to as
          &ldquo;Service&rdquo;).
        </p>
        <p>
          Our Privacy Policy governs your visit to <Link href="http://contextgpt.in" className="text-black underline">https://contextgpt.in</Link>, and explains
          how we collect, safeguard, and disclose information that results from
          your use of our Service.
        </p>
        <p>
          By using Service, you agree to the collection and use of information
          in accordance with this policy. Unless otherwise defined in this
          Privacy Policy, the terms used in this Privacy Policy have the same
          meanings as in our Terms and Conditions.
        </p>
        <p>
          Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all use of our
          Service and, together with the Privacy Policy, constitutes your
          agreement with us (&ldquo;agreement&rdquo;).
        </p>

        <h2>Definitions</h2>
        <p>
          <strong>Service</strong> means the <Link href="http://contextgpt.in" className="text-black underline">https://contextgpt.in</Link> website operated by
          ContextGPT.
        </p>
        <p>
          <strong>Personal Data</strong> means data about a living individual
          who can be identified from those data (or from those and other
          information either in our possession or likely to come into our
          possession).
        </p>
        <p>
          <strong>Usage Data</strong> is data collected automatically either
          generated by the use of Service or from Service infrastructure itself
          (for example, the duration of a page visit).
        </p>
        <p>
          <strong>Cookies</strong> are small files stored on your device
          (computer or mobile device).
        </p>
        <p>
          <strong>Data Controller</strong> means a natural or legal person who
          (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal data are,
          or are to be, processed. For the purpose of this Privacy Policy, we
          are a Data Controller of your data.
        </p>
        <p>
          <strong>Data Processors</strong> (or service providers) means any
          natural or legal person who processes the data on behalf of the Data
          Controller. We may use the services of various Service Providers in
          order to process your data more effectively.
        </p>
        <p>
          <strong>Data Subject</strong> is any living individual who is the
          subject of Personal Data.
        </p>
        <p>
          <strong>The User</strong> is the individual using our Service. The
          User corresponds to the Data Subject, who is the subject of Personal
          Data.
        </p>

        <h2>Information Collection and Use</h2>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>

        <h2>Types of Data Collected</h2>
        <h3>Personal Data</h3>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (&ldquo;Personal Data&rdquo;). Personally identifiable
          information may include, but is not limited to:
        </p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Cookies and Usage Data</li>
        </ul>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials, and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or by
          emailing at{" "}
          <span className="underline text-black font-semibold">support@contextgpt.in</span>.
        </p>

        <h3>Usage Data</h3>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through a mobile
          device (&ldquo;Usage Data&rdquo;). This Usage Data may include
          information such as your computer&rsquo;s Internet Protocol address
          (e.g. IP address), browser type, browser version, the pages of our
          Service that you visit, the time and date of your visit, the time
          spent on those pages, unique device identifiers and other diagnostic
          data.
        </p>
        <p>
          When you access Service with a mobile device, this Usage Data may
          include information such as the type of mobile device you use, your
          mobile device unique ID, the IP address of your mobile device, your
          mobile operating system, the type of mobile Internet browser you use,
          unique device identifiers and other diagnostic data.
        </p>

        <h3>Cookies</h3>
        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p>
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p>Examples of Cookies we use:</p>
        <ul>
          <li>
            <strong>Session Cookies:</strong> We use Session Cookies to operate
            our Service.
          </li>
          <li>
            <strong>Preference Cookies:</strong> We use Preference Cookies to
            remember your preferences and various settings.
          </li>
          <li>
            <strong>Security Cookies:</strong> We use Security Cookies for
            security purposes.
          </li>
          <li>
            <strong>Advertising Cookies:</strong> Advertising Cookies are used
            to serve you with advertisements that may be relevant to you and
            your interests.
          </li>
        </ul>

        <h2>Use of Data</h2>
        <p>ContextGPT uses the collected data for various purposes:</p>
        <ul>
          <li>To provide and maintain our Service;</li>
          <li>To notify you about changes to our Service;</li>
          <li>
            To allow you to participate in interactive features of our Service
            when you choose to do so;
          </li>
          <li>To provide customer support;</li>
          <li>
            To gather analysis or valuable information so that we can improve
            our Service;
          </li>
          <li>To monitor the usage of our Service;</li>
          <li>To detect, prevent and address technical issues;</li>
          <li>
            To fulfill any other purpose for which you provide it;
          </li>
          <li>
            To carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </li>
          <li>
            To provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </li>
          <li>
            To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </li>
          <li>
            In any other way we may describe when you provide the information;
          </li>
          <li>For any other purpose with your consent.</li>
        </ul>

        <h2>Retention of Data</h2>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>

        <h2>Transfer of Data</h2>
        <p>
          Your information, including Personal Data, may be transferred to
          &ndash; and maintained on &ndash; computers located outside of your
          state, province, country, or other governmental jurisdiction where the
          data protection laws may differ from those of your jurisdiction. If
          you are located outside United States and choose to provide
          information to us, please note that we may transfer the data,
          including Personal Data, to United States and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          ContextGPT will take all the steps reasonably necessary to ensure that
          your data is treated securely and in accordance with this Privacy
          Policy, and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>

        <h2>Disclosure of Data</h2>
        <p>
          We may disclose personal information that we collect, or you provide:
        </p>
        <h3>Disclosure for Law Enforcement</h3>
        <p>
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities. 
        </p>
        <h3>Business Transaction</h3>
        <p>
          If we or our subsidiaries are involved in a merger, acquisition, or
          asset sale, your Personal Data may be transferred.
        </p>
        <h3>Other cases</h3>
        <p>We may disclose your information also:</p>
        <ul>
          <li>To fulfill the purpose for which you provide it;</li>
          <li>
            For the purpose of including your company&rsquo;s logo on our
            website;
          </li>
          <li>For any other purpose with your consent.</li>
        </ul>

        <h2>Security of Data</h2>
        <p>
          The security of your data is important to us, but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>

        <h2>
          Your Data Protection Rights Under General Data Protection Regulation
          (GDPR)
        </h2>
        <p>
          If you are a resident of the European Union (EU) and European Economic
          Area (EEA), you have certain data protection rights, covered by GDPR.
        </p>
        <p>
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data.
        </p>
        <p>
          If you wish to be informed what Personal Data we hold about you and if
          you want it to be removed from our systems, please email us at{" "}
          <span className="underline text-black font-semibold">support@contextgpt.in</span>.
        </p>
        <p>
          In certain circumstances, you have the following data protection
          rights:
        </p>
        <ul>
          <li>
            The right to access, update, or delete the information we have on
            you;
          </li>
          <li>
            The right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
          </li>
          <li>
            The right to object. You have the right to object to our processing
            of your Personal Data;
          </li>
          <li>
            The right of restriction. You have the right to request that we
            restrict the processing of your personal information;
          </li>
          <li>
            The right to data portability. You have the right to be provided
            with a copy of your Personal Data in a structured, machine-readable,
            and commonly used format;
          </li>
          <li>
            The right to withdraw consent. You also have the right to withdraw
            your consent at any time where we rely on your consent to process
            your personal information;
          </li>
        </ul>
        <p>
          Please note that we may ask you to verify your identity before
          responding to such requests. Please note that we may not be able to
          provide Service without some necessary data.
        </p>
        <p>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </p>

        <h2>
          Your Data Protection Rights under the California Privacy Protection
          Act (CalOPPA)
        </h2>
        <p>
          IalOPPA is the first state law in the nation to require commercial
          websites and online services to post a privacy policy.
          <br />
          The law’s reach stretches well beyond California to require a person or
          company in the United States (and conceivable the world) that operates
          websites collecting personally identifiable information from California
          consumers to post a conspicuous privacy policy on its website stating
          exactly the information being collected and those individuals with
          whom it is being shared, and to comply with this policy. –
          <br />
          See more at: <span className="text-black underline">
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </span>
        </p>
        <p>According to CalOPPA we agree to the following:</p>
        <ul>
          <li>Users can visit our site anonymously;</li>
          <li>
            Our Privacy Policy link includes the word
            &ldquo;Privacy&rdquo;, and can easily be found on the home page of
            our website;
          </li>
          <li>
            Users will be notified of any privacy policy changes on our Privacy
            Policy Page;
          </li>
          <li>
            Users are able to change their personal information by emailing us
            at{" "}
            <span className="underline text-black font-semibold">support@contextgpt.in</span>.
          </li>
        </ul>

        <h3>Our Policy on &ldquo;Do Not Track&rdquo; Signals</h3>
        <p>
          We honor Do Not Track signals and do not track, plant cookies, or use
          advertising when a Do Not Track browser mechanism is in place. Do Not
          Track is a preference you can set in your web browser to inform
          websites that you do not want to be tracked.
        </p>
        <p>
          You can enable or disable Do Not Track by visiting the Preferences or
          Settings page of your web browser.
        </p>

        <h2>Service Providers</h2>
        <p>
          We may employ third-party companies and individuals to facilitate our
          Service (&ldquo;Service Providers&rdquo;), provide Service on our
          behalf, perform Service-related services, or assist us in analysing
          how our Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>

        <h2>Analytics</h2>
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </p>
        <h3>Google Analytics</h3>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualise and personalise the ads of its own advertising network.
        </p>

        <p>
          For more information on the privacy practices of Google, please visit
           the Google Privacy Terms web page:
            <Link href="https://policies.google.com/privacy?hl=en" className="text-black underline">
              https://policies.google.com/privacy?hl=en
              </Link>
              <br />
              <br />
          We also encourage you to review the Google's policy for safeguarding your data:
          <Link href="https://support.google.com/analytics/answer/6004245">
            https://support.google.com/analytics/answer/6004245
            </Link>
        </p>

        <h2>Service Providers and Subprocessors</h2>
        <p>
          We use third-party service providers to help us deliver our services. A complete list of our current subprocessors is maintained at{" "}
          <Link href="https://contextgpt.in/legal/subprocessors" className="text-black underline">
            contextgpt.in/legal/subprocessors
          </Link>.
        </p>
        <p>Key service providers include:</p>
        <table className="min-w-full border-collapse border border-gray-300">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-300 p-2 text-left">Tool</th>
              <th className="border border-gray-300 p-2 text-left">Privacy Policy</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-gray-300 p-2">OpenAI</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://openai.com/policies/privacy-policy" className="text-black underline">
                  https://openai.com/policies/privacy-policy
                </Link>
              </td>
            </tr>
            {/* <tr>
              <td className="border border-gray-300 p-2">Cohere</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://cohore.com/privacy" className="text-black underline">
                  https://cohore.com/privacy
                </Link>
              </td>
            </tr> */}
            <tr>
              <td className="border border-gray-300 p-2">Amazon Web Services</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://aws.amazon.com/privacy/" className="text-black underline">
                  https://aws.amazon.com/privacy/
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">OpenAI</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://openai.com/policies/privacy-policy" className="text-black underline">
                  https://openai.com/policies/privacy-policy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Firecrawl</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://www.firecrawl.dev/privacy" className="text-black underline">
                  https://www.firecrawl.dev/privacy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Pinecone</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://www.pinecone.io/privacy/" className="text-black underline">
                  https://www.pinecone.io/privacy/
                </Link>
              </td>
            </tr>
            {/* <tr>
              <td className="border border-gray-300 p-2">Prisma</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://www.prisma.io/legal/privacy-policy" className="text-black underline">
                  https://www.prisma.io/legal/privacy-policy
                </Link>
              </td>
            </tr> */}
            {/* <tr>
              <td className="border border-gray-300 p-2">Upstash</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://upstash.com/privacy" className="text-black underline">
                  https://upstash.com/privacy
                </Link>
              </td>
            </tr> */}
            <tr>
              <td className="border border-gray-300 p-2">Polar</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://polar.sh/legal/privacy-policy" className="text-black underline">
                  https://polar.sh/legal/privacy-policy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Resend</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://resend.com/legal/privacy-policy" className="text-black underline">
                  https://resend.com/legal/privacy-policy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">PostHog</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://posthog.com/privacy" className="text-black underline">
                  https://posthog.com/privacy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Supadata</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://supadata.in/privacy" className="text-black underline">
                  https://supadata.in/privacy
                </Link>
              </td>
            </tr>
            {/* <tr>
              <td className="border border-gray-300 p-2">Bento</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://bentonow.com/privacy" className="text-black underline">
                  https://bentonow.com/privacy
                </Link>
              </td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Portkey</td>
              <td className="border border-gray-300 p-2">
                <Link href="https://portkey.in/privacy" className="text-black underline">
                  https://portkey.in/privacy
                </Link>
              </td>
            </tr> */}
          </tbody>
        </table>

        {/* <h2>Visitor Identification and Marketing</h2>
        <p>
          When you visit or log in to our website, cookies and similar technologies may be used by our online data partners or vendors to associate these activities with other personal information they or others have about you, including by association with your email. We use service providers and online marketing and advertising partners for service communications and marketing to these email. You may opt out of receiving this advertising by visiting{" "}
          <Link href="https://app.retention.com/optout" className="text-black underline">
            https://app.retention.com/optout
          </Link>.
        </p> */}

        <h2>Behavioral Remarketing</h2>
        <p>
          ContextGPT may use remarketing services to advertise on third party
          websites to you after you visited our Service. We and our third-party
          vendors use cookies to inform, optimise and serve ads based on your
          past visits to our Service.
        </p>

        <h3>Google Ads (AdWords)</h3>
        <p>
          Google Ads (AdWords) remarketing service is provided by Google Inc.
        </p>
        <p>
          You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page:{" "}
          <Link href="http://www.google.com/settings/ads" className="text-black underline">
            http://www.google.com/settings/ads
          </Link>
        </p>
        <p>
          Google also recommends installing the Google Analytics Opt-out Browser Add-on –{" "}
          <Link href="https://tools.google.com/dlpage/gaoptout" className="text-black underline">
            https://tools.google.com/dlpage/gaoptout
          </Link>{" "}
          – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:{" "}
          <Link href="https://policies.google.com/privacy?hl=en" className="text-black underline">
            https://policies.google.com/privacy?hl=en
          </Link>
        </p>
        <p>
          For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:{" "}
          <Link href="http://www.google.com/settings/ads" className="text-black underline">
            http://www.google.com/settings/ads
          </Link>
        </p>

        <h3>Facebook</h3>
        <p>
          Facebook remarketing service is provided by Facebook Inc.
        </p>
        <p>
          Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page:{" "}
          <Link href="https://www.facebook.com/help/164968693837950" className="text-black underline">
            https://www.facebook.com/help/164968693837950
          </Link>
        </p>
        <p>
          To opt-out from Facebook's interest-based ads, follow these instructions from Facebook:{" "}
          <Link href="https://www.facebook.com/help/568137493302217" className="text-black underline">
            https://www.facebook.com/help/568137493302217
          </Link>
        </p>
        <p>
          Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA{" "}
          <Link href="http://www.aboutads.info/choices/" className="text-black underline">
            http://www.aboutads.info/choices/
          </Link>
          , the Digital Advertising Alliance of Canada in Canada{" "}
          <Link href="http://youradchoices.ca/" className="text-black underline">
            http://youradchoices.ca/
          </Link>{" "}
          or the European Interactive Digital Advertising Alliance in Europe{" "}
          <Link href="http://www.youronlinechoices.eu/" className="text-black underline">
            http://www.youronlinechoices.eu/
          </Link>
          , or opt-out using your mobile device settings.
        </p>
        <p>
          For more information on the privacy practices of Facebook, please visit Facebook's Data Policy:{" "}
          <Link href="https://www.facebook.com/privacy/explanation/" className="text-black underline">
            https://www.facebook.com/privacy/explanation/
          </Link>
        </p>

        <h2>Payments</h2>
        <p>
          We may provide paid products and/or services within Service. In that
          case, we use third-party services for payment processing (e.g. payment
          processors).
        </p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council,
          which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
        </p>
        <p>
          The payment processors we work with are:
        </p>
        <h2>Polar</h2>
          <p>
            Polar is our merchant of record. Their privacy policy can be viewed at{" "}
            <Link href="https://polar.sh/legal/privacy-policy" className="text-black">https://polar.sh/legal/privacy-policy</Link>
          </p>
        <h2>Links to Other Sites</h2>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party&rsquo;s site. We strongly advise you to review the
          Privacy Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>

        <h2>Children&rsquo;s Privacy</h2>
        <p>
          Our Services are not intended for use by children under the age of 18
          (&ldquo;Child&rdquo; or &ldquo;Children&rdquo;).
        </p>
        <p>
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from Children without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>

        <h2>Changes to This Privacy Policy</h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact us
          by email:{" "}
          <span className="underline text-black font-semibold">support@contextgpt.in</span>.
        </p>
      </article>
    </div>
  );
}
