"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Crisp";

const FAQS = [
  {
    question: "How do I connect Crisp with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose Crisp, authorize securely via 1-click OAuth, and select the chat transcripts or help center articles you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What Crisp data can ContextGPT read?",
    answer:
      "ContextGPT can index your Crisp help center articles and past chat conversation transcripts, turning them into a searchable knowledge base your chatbot can actually reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit content in Crisp?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest help articles and conversations in Crisp.",
  },
  {
    question: "Is my Crisp data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Crisp OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your chat data is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the Crisp integration included in the free trial?",
    answer:
      "Yes! Crisp is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Crisp under Data Sources",
  "Authenticate securely using 1-click Crisp OAuth",
  "Select the specific help center articles or chat transcripts to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a help article or close a new chat in Crisp, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Help Center & Chat Context",
    description:
      "Native parsing for Crisp help center articles and historical chat conversation transcripts.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which Crisp content ContextGPT can access. Keep sensitive conversations private while publishing public help articles.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact Crisp articles.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Crisp OAuth authorization. Your chat data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your Crisp data, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in Crisp,",
    rest: " scattered across help articles and past chat transcripts no visitor can search",
    chatMessage: "Why is having answers buried in Crisp a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Your team answers the same chat questions daily,",
    rest: " typing out the same reply over and over instead of reusing what's already in Crisp",
    chatMessage: "How can ContextGPT stop my team from manually retyping the same Crisp answers?",
  },
  {
    bold: "Crisp content changes constantly,",
    rest: " but your website and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my Crisp content changes?",
  },
  {
    bold: "A slow answer loses the lead,",
    rest: " even when the correct information was sitting in your Crisp help center the whole time",
    chatMessage: "How does ContextGPT turn my Crisp content into instant answers so I stop losing leads?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Crisp and train your AI straight from your existing help articles and chat history",
    chatMessage: "How can I get ContextGPT set up with Crisp in just 5 minutes?",
  },
  {
    bold: "Turn Crisp into instant answers:",
    rest: " every help article and past conversation becomes something visitors can actually query",
    chatMessage: "How does ContextGPT turn my Crisp content into instant answers for visitors?",
  },
  {
    bold: "Capture leads around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your Crisp",
    chatMessage: "How can ContextGPT capture leads for my business 24/7 using my Crisp content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit an article in Crisp and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in Crisp?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Crisp sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Crisp ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every help center article and chat transcript inside Crisp into an intelligent, self-learning AI chatbot. Automatically sync team knowledge and answer customer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            So, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Crisp</span> to ChatGPT or maybe Gemini or
            Claude or maybe some other LLMs, and get real answers pulled straight from your own help
            center and chat data. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your Crisp, we ingest your help center articles and past
            chat transcripts, and turn them into a searchable knowledge base your chatbot can actually
            reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual Crisp data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing leads right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a lead</strong> if you respond within 5
          minutes — but most service businesses take hours.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Crisp with ChatGPT?"
      featuresSubheading="Eliminate outdated help articles and repetitive chat replies. Turn your existing Crisp content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
