<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 2rem;
          }
          #content {
            max-width: 1000px;
            margin: 0 auto;
          }
          h1 {
            color: #111;
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 1rem;
          }
          p {
            font-size: 1.1rem;
            color: #444;
            margin-bottom: 2rem;
          }
          a {
            color: #3b82f6;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.95rem;
          }
          th {
            text-align: left;
            border-bottom: 2px solid #ddd;
            padding: 10px;
            color: #111;
            font-weight: 600;
          }
          td {
            padding: 10px;
            border-bottom: 1px solid #eee;
          }
          tr:nth-child(odd) td {
            background-color: #f9fafb;
          }
          .back-link {
            display: inline-block;
            margin-bottom: 1rem;
            font-size: 1rem;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>XML Sitemap</h1>
          <p>
            This is a sitemap generated by <a href="https://contextgpt.co">ContextGPT</a> to allow search engines to discover this website's content.
          </p>
          
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <table>
              <thead>
                <tr>
                  <th>Sitemap</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <xsl:variable name="sitemapURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                      <a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <a href="/sitemap.xml" class="back-link">&#8592; Back to index</a>
            <table>
              <thead>
                <tr>
                  <th>URL (<xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> total)</th>
                  <th>Images</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                      <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td>
                      <xsl:value-of select="count(image:image)"/>
                    </td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
            <br />
            <a href="/sitemap.xml" class="back-link">&#8592; Back to index</a>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
