"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Facebook Messenger";

const FAQS = [
  {
    question: "How do I connect Facebook Messenger with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Deploy Channels, choose Facebook Messenger, authorize securely via 1-click OAuth, and connect the Facebook Page you want the chatbot to respond on. Your trained chatbot goes live in your Page inbox automatically.",
  },
  {
    question: "Does Facebook Messenger act as a data source or a deployment channel?",
    answer:
      "Facebook Messenger is a deployment channel. ContextGPT answers inside your Page's Messenger inbox using the same knowledge base you've already trained across your other channels.",
  },
  {
    question: "Will customers know they're talking to a chatbot?",
    answer:
      "You're in full control. You can customize the chatbot's introduction and tone, and set up seamless handoff to a human teammate whenever a conversation needs a real person.",
  },
  {
    question: "Can I use Facebook Messenger alongside other chat channels?",
    answer:
      "Yes! Facebook Messenger can run alongside Slack, WhatsApp, and other deployment channels, all powered by the exact same trained knowledge base.",
  },
  {
    question: "Is the Facebook Messenger integration included in the free trial?",
    answer:
      "Yes! Facebook Messenger is available as a core deployment channel across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Facebook Messenger under Deploy Channels",
  "Authenticate securely using 1-click Facebook OAuth",
  "Connect the Facebook Page you want the chatbot to respond on",
  "Customize the chatbot's greeting, tone, and escalation rules",
  "Go live and let ContextGPT handle incoming Facebook Messenger conversations",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update your knowledge base anywhere, hit resync, and your Messenger conversations instantly reflect the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Conversation Context",
    description:
      "Native support for product FAQs, support articles, and CRM notes, so every Messenger reply stays consistent and on-brand.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly what knowledge ContextGPT can share through Messenger. Keep sensitive information private while publishing public answers.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so your team can verify answers against your exact source records.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Facebook OAuth authorization. Conversation data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained, deploy the same chatbot to Facebook Messenger, your Website, Slack, WhatsApp, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers never reach the customer,",
    rest: " because no one is watching the Facebook Page inbox around the clock",
    chatMessage: "Why do Facebook Messenger replies take hours when my team is offline, and how does ContextGPT fix that?",
  },
  {
    bold: "Customers ask questions your team answers manually,",
    rest: " typing the same reply over and over inside Messenger",
    chatMessage: "How can ContextGPT stop my team from manually typing the same answers in Facebook Messenger?",
  },
  {
    bold: "Different agents give different answers,",
    rest: " leaving customers with inconsistent, off-brand replies to the same question",
    chatMessage: "What's the risk of inconsistent answers when different agents reply to the same Messenger question?",
  },
  {
    bold: "A slow reply loses the lead,",
    rest: " even when the correct information was sitting in your knowledge base the whole time",
    chatMessage: "How does ContextGPT turn my Facebook Page into instant answers so I stop losing leads?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Facebook Messenger and let your AI respond straight from your existing knowledge base",
    chatMessage: "How can I get ContextGPT set up with Facebook Messenger in just 5 minutes?",
  },
  {
    bold: "Turn every message into an instant answer:",
    rest: " no customer waits hours for a reply that was already sitting in your knowledge base",
    chatMessage: "How does ContextGPT answer Facebook Messenger conversations instantly, 24/7?",
  },
  {
    bold: "Capture leads around the clock:",
    rest: " even when your team is busy, offline, or asleep, no message ever goes unanswered",
    chatMessage: "How does ContextGPT make sure no Facebook Page message or lead ever goes unanswered?",
  },
  {
    bold: "Always consistent:",
    rest: " one trained knowledge base keeps every Messenger answer accurate and on-brand",
    chatMessage: "How does one trained knowledge base keep Messenger answers consistent every time?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Facebook Messenger connection?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language conversations?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Facebook Messenger ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Deploy an intelligent, self-learning AI chatbot straight inside your Facebook Page's Messenger inbox. Answer customer questions instantly, day or night, with verifiable source citations and seamless human handoff."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Facebook Messenger</span> to ChatGPT or
            maybe Gemini or Claude or maybe some other LLMs, and get real answers delivered straight
            through your Page inbox. <span className="whitespace-nowrap">Good news</span> —
            you&apos;ve landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You train us on your product info, support content, and CRM notes, we
            deploy it straight into your Facebook Messenger inbox, and turn every conversation into
            something your AI can actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual trained knowledge base
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is also on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              WhatsApp
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho SalesIQ
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing leads right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a lead</strong> if you respond within 5
          minutes — but most teams take hours to reply on Messenger.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Facebook Messenger with ChatGPT?"
      featuresSubheading="Eliminate slow manual replies and missed messages. Deploy an automated AI agent straight inside the Messenger inbox you already use."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
