"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "iCloud";

const FAQS = [
  {
    question: "How do I connect iCloud with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose iCloud, authorize securely via 1-click OAuth, and select the files or folders you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What iCloud data can ContextGPT read?",
    answer:
      "ContextGPT can index documents, PDFs, and text-based files stored in your iCloud Drive folders, turning them into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit iCloud files?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in iCloud Drive.",
  },
  {
    question: "Is my iCloud data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official iCloud OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your files are never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the iCloud integration included in the free trial?",
    answer:
      "Yes! iCloud is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select iCloud under Data Sources",
  "Authenticate securely using 1-click iCloud OAuth",
  "Select the specific files or folders in iCloud Drive to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a file or folder in iCloud Drive, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full File Context",
    description:
      "Native parsing for documents, PDFs, and text-based files stored across your iCloud Drive folders.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which iCloud folders ContextGPT can access. Keep personal files private while publishing shared documents.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact iCloud files.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure iCloud OAuth authorization. Your files are encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your iCloud files, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in iCloud,",
    rest: " scattered across folders and files no visitor or teammate can search",
    chatMessage: "Why is having answers buried in iCloud a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "People ask questions your files already answer,",
    rest: " and you end up digging through iCloud Drive folders to find the right document",
    chatMessage: "How can ContextGPT stop me from manually digging through iCloud files to answer questions?",
  },
  {
    bold: "iCloud content changes constantly,",
    rest: " but the answers people get quietly go stale as files are updated",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my iCloud content changes?",
  },
  {
    bold: "A slow answer loses the moment,",
    rest: " even when the correct information was sitting in your iCloud Drive the whole time",
    chatMessage: "How does ContextGPT turn my iCloud files into instant answers so I stop losing time?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect iCloud and train your AI straight from your existing documents and files",
    chatMessage: "How can I get ContextGPT set up with iCloud in just 5 minutes?",
  },
  {
    bold: "Turn iCloud into instant answers:",
    rest: " every document and file becomes something people can actually query",
    chatMessage: "How does ContextGPT turn my iCloud files into instant answers?",
  },
  {
    bold: "Get answers around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your iCloud Drive",
    chatMessage: "How can ContextGPT provide 24/7 answers using my iCloud content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a file in iCloud and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in iCloud?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the iCloud sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="iCloud ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every document and file stored inside iCloud Drive into an intelligent, self-learning AI chatbot. Automatically sync your files and answer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">iCloud</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            files. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your iCloud Drive, we ingest your documents and files,
            and turn them into a searchable knowledge base your chatbot can actually reason over.{" "}
            <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual iCloud data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing time right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to get things done</strong> if you can find a file in
          seconds — but most people take minutes digging through folders.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect iCloud with ChatGPT?"
      featuresSubheading="Eliminate manual file digging and repeated searching. Turn your existing iCloud content straight into an automated AI assistant."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
