"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Slack";

const FAQS = [
  {
    question: "How do I connect Slack with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose Slack, authorize securely via 1-click OAuth, and select the channels you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What Slack content can ContextGPT read?",
    answer:
      "ContextGPT can index messages and threads from the channels you select, turning your team's internal discussions and decisions into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when new messages are posted in Slack?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest conversations in Slack.",
  },
  {
    question: "Is my Slack data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Slack OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your workspace conversations are never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the Slack integration included in the free trial?",
    answer:
      "Yes! Slack is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Slack under Data Sources",
  "Authenticate securely using 1-click Slack OAuth",
  "Select the specific channels to index into your knowledge base",
  "Let ContextGPT extract messages, chunk threads, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack itself, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "New replies land in a Slack thread, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Channel Context",
    description:
      "Native parsing for Slack channel messages and threads, so decisions and know-how never get lost in scroll history.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which Slack channels ContextGPT can access. Keep private channels out while indexing shared knowledge channels.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact Slack threads.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Slack OAuth authorization. Your workspace data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your Slack data, deploy your chatbot to your Website, Slack itself, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in Slack,",
    rest: " scattered across channels and threads no visitor can search",
    chatMessage: "Why is having answers buried in Slack a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Teammates ask questions your team answers manually,",
    rest: " retyping the same reply in a thread over and over",
    chatMessage: "How can ContextGPT stop my team from manually retyping Slack answers?",
  },
  {
    bold: "Slack conversations pile up constantly,",
    rest: " but your onboarding and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate as Slack conversations pile up?",
  },
  {
    bold: "A slow answer loses the moment,",
    rest: " even when the correct information was sitting in a Slack thread the whole time",
    chatMessage: "How does ContextGPT turn my Slack content into instant answers so I stop losing time?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Slack and train your AI straight from your existing channels and threads",
    chatMessage: "How can I get ContextGPT set up with Slack in just 5 minutes?",
  },
  {
    bold: "Turn Slack into instant answers:",
    rest: " every message and thread becomes something people can actually query",
    chatMessage: "How does ContextGPT turn my Slack content into instant answers?",
  },
  {
    bold: "Support your team around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your Slack",
    chatMessage: "How can ContextGPT support my team 24/7 using my Slack content?",
  },
  {
    bold: "Always up to date:",
    rest: " new messages land in Slack and your chatbot's answers update right along with them",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when new messages come in on Slack?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Slack sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Slack ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every channel message and thread inside Slack into an intelligent, self-learning AI chatbot. Automatically sync team knowledge and answer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Slack</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            team conversations. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your Slack workspace, we ingest your channel messages
            and threads, and turn them into a searchable knowledge base your chatbot can
            actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual Slack conversations
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Notion
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              HubSpot
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              SharePoint
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing time right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to keep someone engaged</strong> if you answer within 5
          minutes — but most teams take hours scrolling through Slack.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Slack with ChatGPT?"
      featuresSubheading="Eliminate lost threads and manual answer re-typing. Turn your existing Slack conversations straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
