"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "GitBook";

const FAQS = [
  {
    question: "How do I connect GitBook with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose GitBook, authorize securely via 1-click OAuth, and select the spaces or collections you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What GitBook content can ContextGPT read?",
    answer:
      "ContextGPT can index your public or private GitBook spaces, including docs pages, API reference guides, and nested collections, turning them into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit GitBook content?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest edits made in GitBook.",
  },
  {
    question: "Is my GitBook data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official GitBook OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your documentation is never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the GitBook integration included in the free trial?",
    answer:
      "Yes! GitBook is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select GitBook under Data Sources",
  "Authenticate securely using 1-click GitBook OAuth",
  "Select the specific GitBook spaces or pages to index into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or docs portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a page or collection in GitBook, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Documentation Context",
    description:
      "Native parsing for GitBook spaces, nested collections, API reference pages, and technical guides.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which GitBook spaces ContextGPT can access. Keep internal drafts private while publishing public docs.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact GitBook pages.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure GitBook OAuth authorization. Your documentation is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your GitBook content, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in GitBook,",
    rest: " scattered across spaces, nested collections, and pages no visitor wants to click through",
    chatMessage: "Why is having answers buried in GitBook a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Users ask questions your docs already answer,",
    rest: " but they give up before finding the right page in your GitBook space",
    chatMessage: "How can ContextGPT stop users from giving up on finding answers in my GitBook docs?",
  },
  {
    bold: "GitBook content changes constantly,",
    rest: " but your support answers and onboarding guides quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my GitBook content changes?",
  },
  {
    bold: "A slow answer loses the user,",
    rest: " even when the correct information was sitting in your GitBook the whole time",
    chatMessage: "How does ContextGPT turn my GitBook content into instant answers so I stop losing users?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect GitBook and train your AI straight from your existing docs and guides",
    chatMessage: "How can I get ContextGPT set up with GitBook in just 5 minutes?",
  },
  {
    bold: "Turn GitBook into instant answers:",
    rest: " every page, collection, and guide becomes something users can actually query",
    chatMessage: "How does ContextGPT turn my GitBook content into instant answers for users?",
  },
  {
    bold: "Support users around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your GitBook",
    chatMessage: "How can ContextGPT support my users 24/7 using my GitBook content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a page in GitBook and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in GitBook?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the GitBook sync?" },
  { text: "Auto-Resync on Content Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="GitBook ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every page, collection, and guide inside GitBook into an intelligent, self-learning AI chatbot. Automatically sync your documentation and answer user questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">GitBook</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            documentation. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your GitBook, we ingest your spaces, collections, and
            pages, and turn them into a searchable knowledge base your chatbot can actually reason
            over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual GitBook data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing users right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a visitor</strong> if you answer within 5
          minutes — but most documentation sites take hours to find the right page.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect GitBook with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual support re-writing. Turn your existing GitBook content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
