"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "Dropbox";

const FAQS = [
  {
    question: "How do I connect Dropbox with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose Dropbox, authorize securely via 1-click OAuth, and select the folders or files you want your chatbot to learn from. Indexing begins automatically.",
  },
  {
    question: "What Dropbox data can ContextGPT read?",
    answer:
      "ContextGPT can index documents, spreadsheets, presentations, PDFs, and folders stored in your Dropbox account, turning them into a searchable knowledge base your chatbot can actually reason over.",
  },
  {
    question: "Will the chatbot update automatically when I edit files in Dropbox?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or set automatic sync schedules so your chatbot's knowledge base always reflects the newest files and edits made in Dropbox.",
  },
  {
    question: "Is my Dropbox data secure and private?",
    answer:
      "Absolutely. ContextGPT uses official Dropbox OAuth scopes, standard AES-256 encryption at rest, and strict data privacy controls. Your files are never stored insecurely or used to train public LLM models.",
  },
  {
    question: "Is the Dropbox integration included in the free trial?",
    answer:
      "Yes! Dropbox is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select Dropbox under Data Sources",
  "Authenticate securely using 1-click Dropbox OAuth",
  "Select the specific folders or files you want indexed into your knowledge base",
  "Let ContextGPT extract text, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Update a file or folder in Dropbox, hit resync, and your chatbot instantly answers with the newest info without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Broad File Format Support",
    description:
      "Native parsing for PDFs, Word docs, spreadsheets, presentations, and other files stored across your Dropbox folders.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which Dropbox folders ContextGPT can access. Keep sensitive files private while publishing shared documentation.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against your exact Dropbox files.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure Dropbox OAuth authorization. Your files are encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your Dropbox data, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best answers are buried in Dropbox,",
    rest: " scattered across folders, subfolders, and files no visitor can search",
    chatMessage: "Why is having answers buried in Dropbox a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Your team hunts through folders for the right file,",
    rest: " then copy-pastes the same document link over and over to answer the same question",
    chatMessage: "How can ContextGPT stop my team from manually digging through Dropbox folders?",
  },
  {
    bold: "Dropbox files change constantly,",
    rest: " but your website and support answers quietly go stale",
    chatMessage: "How does ContextGPT make sure answers stay accurate when my Dropbox files change?",
  },
  {
    bold: "A slow answer loses the lead,",
    rest: " even when the correct information was sitting in your Dropbox the whole time",
    chatMessage: "How does ContextGPT turn my Dropbox content into instant answers so I stop losing leads?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect Dropbox and train your AI straight from your existing files and folders",
    chatMessage: "How can I get ContextGPT set up with Dropbox in just 5 minutes?",
  },
  {
    bold: "Turn Dropbox into instant answers:",
    rest: " every document, spreadsheet, and file becomes something users can actually query",
    chatMessage: "How does ContextGPT turn my Dropbox content into instant answers?",
  },
  {
    bold: "Capture leads around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your Dropbox",
    chatMessage: "How can ContextGPT capture leads for my business 24/7 using my Dropbox content?",
  },
  {
    bold: "Always up to date:",
    rest: " edit a file in Dropbox and your chatbot's answers update right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I update content in Dropbox?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the Dropbox sync?" },
  { text: "Auto-Resync on File Edits", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language documents?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="Dropbox ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every file, folder, and document inside Dropbox into an intelligent, self-learning AI chatbot. Automatically sync team knowledge and answer customer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            So, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">Dropbox</span> to ChatGPT or maybe Gemini or
            Claude or maybe some other LLMs, and get real answers pulled straight from your own files.{" "}
            <span className="whitespace-nowrap">Good news</span> — you&apos;ve landed in the right
            place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your Dropbox, we ingest your documents, spreadsheets,
            presentations, and folders, and turn them into a searchable knowledge base your chatbot can
            actually reason over. <br />
            Your content changed? No problem, using Auto-Synchronization the knowledge base is updated
            regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual Dropbox data
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why you're losing leads right now"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a lead</strong> if you respond within 5
          minutes — but most service businesses take hours.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect Dropbox with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual file hunting. Turn your existing Dropbox content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
