"use client";

import IntegrationDetailPage from "../IntegrationDetailPage";
import {
  AutomationIcon,
  CitedSourcesIcon,
  RbacIcon,
  ApiIcon,
  DataEncryptionIcon,
  IntegrationsIcon,
} from "../../../../../public/icons/IconSvg";

const NAME = "YouTube";

const FAQS = [
  {
    question: "How do I connect YouTube with ChatGPT / ContextGPT?",
    answer:
      "In your ContextGPT dashboard, navigate to Data Sources, choose YouTube, and paste in the video or channel link you want indexed. ContextGPT pulls the transcript and begins indexing automatically.",
  },
  {
    question: "What YouTube content can ContextGPT read?",
    answer:
      "ContextGPT extracts transcripts and captions from your YouTube videos, tutorials, product walkthroughs, and webinars, turning the spoken content into a searchable knowledge base your chatbot can reason over.",
  },
  {
    question: "Does my video need captions enabled for this to work?",
    answer:
      "ContextGPT pulls from available captions or auto-generated transcripts, so most public videos work out of the box without any extra setup on your end.",
  },
  {
    question: "Will the chatbot update automatically when I publish new videos?",
    answer:
      "Yes! You can trigger a 1-click resync from your dashboard or add new videos and channels anytime so your chatbot's knowledge base keeps growing with your content.",
  },
  {
    question: "Is the YouTube integration included in the free trial?",
    answer:
      "Yes! YouTube is available as a core data source across all ContextGPT plans, and you can test it with a 7-day risk-free trial.",
  },
];

const STEPS = [
  "Open your ContextGPT dashboard and select YouTube under Data Sources",
  "Paste in the video or channel link you want indexed",
  "Select the specific videos to pull into your knowledge base",
  "Let ContextGPT extract the transcript, chunk content, and generate AI vector embeddings",
  "Deploy your trained AI chatbot to your website, Slack, WhatsApp, or customer support portal",
];

const FEATURES = [
  {
    title: "Real-Time Auto Resync",
    description:
      "Publish a new video or update one in YouTube, hit resync, and your chatbot instantly answers with the newest transcript without manual copy-pasting.",
    icon: AutomationIcon,
  },
  {
    title: "Full Transcript Context",
    description:
      "Native parsing for YouTube captions and auto-generated transcripts across tutorials, walkthroughs, and webinars.",
    icon: CitedSourcesIcon,
  },
  {
    title: "Granular Security & Scope",
    description:
      "Choose exactly which videos or channels ContextGPT can access. Keep internal recordings private while publishing public tutorials.",
    icon: RbacIcon,
  },
  {
    title: "Verifiable Source Citations",
    description:
      "Every response generated by the AI includes direct source citations, so users can verify answers against the exact YouTube video and moment it came from.",
    icon: ApiIcon,
  },
  {
    title: "Enterprise OAuth Encryption",
    description:
      "Secure connection to your YouTube content. Your video data is encrypted with AES-256 and never used to train open LLMs.",
    icon: DataEncryptionIcon,
  },
  {
    title: "Multi-Channel Deployment",
    description:
      "Once trained on your YouTube content, deploy your chatbot to your Website, Slack, WhatsApp, Zendesk, or custom web API.",
    icon: IntegrationsIcon,
  },
];

const problems = [
  {
    bold: "Your best explanations are buried in YouTube,",
    rest: " locked inside hours of video no visitor will ever sit through or search",
    chatMessage: "Why is having answers buried in YouTube videos a problem, and how does ContextGPT fix that?",
  },
  {
    bold: "Viewers ask questions your videos already answer,",
    rest: " but nobody wants to scrub through timestamps to find the right moment",
    chatMessage: "How can ContextGPT stop users from scrubbing through my YouTube videos to find answers?",
  },
  {
    bold: "You publish new videos constantly,",
    rest: " but your website and support answers quietly go stale and don't reflect the latest content",
    chatMessage: "How does ContextGPT make sure answers stay accurate when I publish new YouTube videos?",
  },
  {
    bold: "A slow answer loses the viewer,",
    rest: " even when the correct explanation was sitting in your YouTube video the whole time",
    chatMessage: "How does ContextGPT turn my YouTube videos into instant answers so I stop losing viewers?",
  },
];

const benefits = [
  {
    bold: "Get started in 5 minutes:",
    rest: " connect YouTube and train your AI straight from your existing tutorials and walkthroughs",
    chatMessage: "How can I get ContextGPT set up with YouTube in just 5 minutes?",
  },
  {
    bold: "Turn YouTube into instant answers:",
    rest: " every tutorial, walkthrough, and webinar becomes something viewers can actually query",
    chatMessage: "How does ContextGPT turn my YouTube videos into instant answers for viewers?",
  },
  {
    bold: "Capture attention around the clock:",
    rest: " even when you're busy, offline, or asleep, powered by what's already in your YouTube videos",
    chatMessage: "How can ContextGPT answer viewer questions 24/7 using my YouTube content?",
  },
  {
    bold: "Always up to date:",
    rest: " publish a new video on YouTube and your chatbot's answers grow right along with it",
    chatMessage: "How does ContextGPT keep chatbot answers in sync when I publish new YouTube videos?",
  },
];

const microBar = [
  { text: "7-day risk-free trial", msg: "Tell me about the 7-day free trial." },
  { text: "OAuth 2.0 Secure Sync", msg: "How secure is the YouTube sync?" },
  { text: "Auto-Resync on New Videos", msg: "How does real-time resync work?" },
  { text: "100+ Global Languages", msg: "Does ContextGPT support multi-language transcripts?" },
];

export default function Page() {
  return (
    <IntegrationDetailPage
      name={NAME}
      breadcrumbLabel="YouTube ChatGPT Integration"
      heroTitleSuffix="to ChatGPT"
      heroSubtitle="Turn every tutorial, product walkthrough, and webinar sitting on YouTube into an intelligent, self-learning AI chatbot. Automatically sync video transcripts and answer viewer questions instantly with verifiable source citations."
      microBar={microBar}
      narrative={{
        paragraph1: (
          <>
            o, if you&apos;re reading this, then you&apos;ve been surfing around the internet for a
            straightforward way to connect{" "}
            <span className="font-semibold text-[#155ded]">YouTube</span> to ChatGPT or maybe Gemini
            or Claude or maybe some other LLMs, and get real answers pulled straight from your own
            video content. <span className="whitespace-nowrap">Good news</span> — you&apos;ve
            landed in the right place.
          </>
        ),
        infoBoxText: (
          <>
            At <span className="font-semibold text-slate-900">ContextGPT</span>, we built exactly this
            kind of solution. You point us at your YouTube videos or channel, we pull the transcripts
            and captions, and turn them into a searchable knowledge base your chatbot can actually
            reason over. <br />
            Published a new video? No problem, using Auto-Synchronization the knowledge base is
            updated regularly, no irrelevant answers based on the internet.
          </>
        ),
        paragraph2: (
          <>
            Under the hood, we let you choose from the leading LLMs on the market, so you&apos;re never
            locked into one model&apos;s quirks or pricing. Whether that&apos;s the latest GPT release
            or another frontier model, ContextGPT handles the retrieval and citation work so the model
            always answers from{" "}
            <span className="border-b-2 border-[#155ded]/30 font-medium text-slate-800">
              your actual YouTube content
            </span>
            , not a guess. If you&apos;ve been putting off setting this up because it sounded
            complicated, it isn&apos;t.{" "}
            <span className="font-semibold text-slate-900">Give it five minutes</span> and you&apos;ll
            see what we mean.
          </>
        ),
        paragraph3: (
          <>
            And the best part is that if your team is on{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-blue-500 text-black">
              Slack
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-green-500 text-black">
              Zendesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-orange-500 text-black">
              Freshdesk
            </span>
            ,{" "}
            <span className="tracking-wide font-semibold underline underline-offset-4 decoration-purple-500 text-black">
              Zoho
            </span>{" "}
            or maybe some other place, you can straight away connect that into ContextGPT and get
            answers there :). Checkout{" "}
            <a href="/integration" className="text-[#155ded] hover:underline">
              Integrations
            </a>{" "}
            for the full list of supported integrations.
          </>
        ),
      }}
      problemsHeading="Why your videos aren't working as hard as they should"
      problemsSubheading={
        <>
          You&apos;re <strong>100x more likely to convert a viewer</strong> if you answer their
          question within seconds — but scrubbing through a video takes minutes.
        </>
      }
      problems={problems}
      solutionHeading="ContextGPT gives you an unfair advantage"
      benefits={benefits}
      featuresHeading="Why Connect YouTube with ChatGPT?"
      featuresSubheading="Eliminate outdated documentation and manual video re-explaining. Turn your existing YouTube content straight into an automated AI support agent."
      features={FEATURES}
      faqs={FAQS}
      steps={STEPS}
    />
  );
}
